server:
  port: 7999

spring:
  application:
    name: microServiceRealBattleAdmin
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka-01:8080/eureka/,http://eureka-02:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS




